config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'about', to: 'static_pages#about'
  resources :articles
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, only: [:new, :create, :index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6 }
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :article, through: :article_categories

end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  validates :name, presence: true,
                   length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP
  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { minimum: 3, maximum: 25 },
                    format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :isLoggedIn?
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def isLoggedIn?
    !!current_user
  end

  def require_user
    unless isLoggedIn?
      flash[:alert] = 'You are not logged in'
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article created successfully'
      redirect_to @article
    else
      render :new
    end
  end

  def edit

  end

  def update
    @article.user ||= current_user
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = 'Article updated successfully'
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You dont have permission to perform this action'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  before_action :require_admin, only: %i[new create]
  def index; end

  def new
    @category = Category.new
  end

    def show 
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'Create category successfully'
      redirect_to @category
    else
      render :new
    end
  end



  private
  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
   unless isLoggedIn? && current_user.admin?
    flash[:alert] = "You have to be admin to create category"
    redirect_to categories_path
  end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Login successfully'
      redirect_to user
    else
      flash.now[:alert] = 'There was a problem'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Log out'
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to articles_path if isLoggedIn?
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to articles_path, notice: "Welcome #{@user.name}" }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to articles_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user 
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # USE callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = 'You dont have permission to perform this action'
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}"
    image_tag(gravatar_url, alt: user.name)
  end
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h2>The following errors prevented the article from being saved</h2>
  <ul>
<% @article.errors.full_messages.each do |msg| %>
  <li>
  <%= msg %>
</li>
    <% end %>
  </ul>
<% end %>
<%= form_with(model: article,  local: true) do |f|  %>
  <p>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :description%>
  <%= f.text_area :description%>
  </p>
  <p>
  <%= f.label :category %>
  <%= f.collection_select(:category_ids, Category.all, :id, :name) %>
  </p>
  <p>
<%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit</h1>
<%= render 'form', article: @article %>
<td><%= link_to "Return to article list", articles_path %></td>

app/views/articles/index.html.erb
<div>
Articles listing page
</div>
<div class="flickr_pagination">
    <%= will_paginate @posts, :container => false %>
</div>

<table>
<thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Author</th>
    <th colspan="3">Actions</th>
  </tr>
</thead>  
<tbody>
  <% @articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.description %></td>
    <td><%= article.user.name if article.user %></td>
    <td><%= link_to "Show", article_path(article) %></td>
    <% if isLoggedIn? && (article.user == current_user || current_user.admin?) %>
    <td><%= link_to "Edit", edit_article_path(article) %></td>
    <td><%= link_to "Delete", article_path(article), method: :delete , data:{confirm: "Are you pretty sure?"}%></td>
    <% end %>
  </tr>
<% end %>
</tbody>
</table>
<%= link_to "Create new article", new_article_path%>
<% if isLoggedIn? %>
  <%= link_to 'Log out ', logout_path, method: :delete %>
<% end %>

app/views/articles/new.html.erb
<h1>New</h1>
<%= render "form", article: @article %>
<td><%= link_to "Return to article list", articles_path %></td>

app/views/articles/show.html.erb
<h1>Show article</h1>
<p><strong> TItle: </strong><%= @article.title %></p>
<p>by <%= @article.user.name if @article.user  %></p>
<p><strong> Description: </strong><%= @article.description %></p>
<% if isLoggedIn? && (@article.user == current_user || current_user.admin?)  %>
  <td><%= link_to "Edit", edit_article_path(@article) %></td>
  <td><%= link_to "Delete", article_path(@article), method: :delete, data:{confirm: "Are you pretty sure?"} %></td>
<% end %>
<td><%= link_to "Return to article list", articles_path %></td>
<% if isLoggedIn? %>
<%= link_to 'Log out ', logout_path, method: :delete %>
<% end%>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(category.errors.count, "error" ) %> prohibited this user from being saved:
      </h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :name %>
          <%= form.text_field :name , placeholder:"Enter new category" %>
      </div>

      <div class="actions">
        <%= form.submit "Create new category" %>
      </div>
      <% end %>

app/views/categories/new.html.erb
<h1>Create new category</h1>

<%= render 'form', category: @category%>

<%= link_to 'Back to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
    <% flash.each do |name,msg| %>
      <%= msg %>
    <% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUDApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=  render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>
<%= link_to "Home" ,root_path %>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

<%= link_to "About" ,about_path %>
<%= link_to "Articles", articles_path %>
<%= link_to "Sign up", signup_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(user.errors.count, "error" ) %> prohibited this user from being saved:
      </h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :name %>
          <%= form.text_field :name , placeholder:"Enter your name" %>
      </div>

      <div class="field">
        <%= form.label :email %>
          <%= form.email_field :email, placeholder:"Enter your email" %>

      </div>

      <div class="field">
        <%= form.label :password %>
          <%= form.password_field :password, placeholder:"Enter your password" %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
    <% if isLoggedIn?  %>
     <% if user == current_user  %> 
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <% end %>
        <% if current_user.admin? %>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', signup_path %>

app/views/users/new.html.erb
<h1>Sign up </h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'List users', users_path %>
<%= gravatar_for @user %>
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<% if @user == current_user %>
  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Delete', user_path(@user), method: :delete %> |
<% end %>
<%= link_to 'Log out ', logout_path, method: :delete %>